### PR TITLE
Sort search_tx by height to ensure consistent order

### LINKED ISSUE #500: "Get and watch atomic swap lifecycle" fails
There is a [CI fail on master](https://travis-ci.com/iov-one/iov-core/jobs/156630105) after [an unrelated change](https://github.com/iov-one/iov-core/compare/d34def4cd6ceb8...2875add6077d65):

```
1. Integration tests with bov+tendermint : Get and watch atomic swap lifecycle
   Expected $['7'] = 2 to equal 4.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:689:27
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected 'open' to equal 'claimed'.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:690:25
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected $['7'] = 4 to equal 3.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:691:28
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected $['7'] = 3 to equal 2.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:693:28
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
```

This smells like an indetermined order of results in

```ts
    const finalSwaps = await connection.getSwap({ recipient: rcptAddr });
    expect(finalSwaps.data.length).toEqual(3);
    const [open3, claim2, claim1] = finalSwaps.data;
```

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #500 

It seems like tendermint sorts height by strings sometimes....
Do a numeric sort client-side to ensure consistent, expected ordering of transactions for search_tx

### CODE REVIEW

**Comment by ethanfrey** [comment]
@webmaster128 updated the code according to comments, please review again

File: packages/iov-tendermint-rpc/src/client.ts [hunk 1]
```diff
@@ -129,27 +129,33 @@ export class Client {
...
   }
 
-  public txSearch(params: requests.TxSearchParams): Promise<responses.TxSearchResponse> {
+  public async txSearch(params: requests.TxSearchParams): Promise<responses.TxSearchResponse> {
     const query: requests.TxSearchRequest = { params, method: requests.Method.TX_SEARCH };
-    return this.doCall(query, this.p.encodeTxSearch, this.r.decodeTxSearch);
+    const resp = await this.doCall(query, this.p.encodeTxSearch, this.r.decodeTxSearch);
+    return {
+      ...resp,
+      txs: [...resp.txs].sort((a, b) => a.height - b.height),
```
Comment (webmaster128) [inline packages/iov-tendermint-rpc/src/client.ts]: When I see this I whish we could do Swift, where you have strict naming and `.sort()` mutates an array and `.soreted()` returns a sorted copy … But this looks correct and the best we can get out of TypeScript.

File: packages/iov-bns/src/bnsconnection.ts [hunk 2]
```diff
@@ -303,6 +305,7 @@ export class BnsConnection implements BcpAtomicSwapConnection {
       result: txResult.data || new Uint8Array([]),
       ...this.codec.parseBytes(tx, chainId),
     });
+    // make sure we sort by height, as tendermint may be sorting by string value of the height
```
Comment (webmaster128) [inline packages/iov-bns/src/bnsconnection.ts]: This comment should move to the sorting
